# Generated by Django 3.0.7 on 2020-06-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.TextField(choices=[('cash', 'Cash'), ('credit_cart', 'Credit Cart'), ('bank_transfer', 'Bank Transfer')], default='Cash'),
        ),
    ]
